services:
  app:
    image: elixir:1.16
    container_name: app
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - dependencies:/usr/local/deps
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ./entrypoint.sh
    command: mix phx.server

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  dependencies:
  database:
